### ISSUE TITLE
The spec of the Todo app

### ISSUE THREAD

**Issue by tkeiyama** [tkeiyama/best-todo-app#1]
The following functionalities are the given spec.
So they might be changed.

## Functionalities

These functionalities are marked as complete when both the Frontend and the Item service worked correctly.

- [x] add an item https://github.com/tkeiyama/best-todo-app/issues/3 https://github.com/tkeiyama/best-todo-app/issues/12
- [x] edit an item https://github.com/tkeiyama/best-todo-app/issues/6 https://github.com/tkeiyama/best-todo-app/issues/13
- [x] mark/unmark item(s) as complete https://github.com/tkeiyama/best-todo-app/issues/8 https://github.com/tkeiyama/best-todo-app/issues/13
- [x] remove item(s)  https://github.com/tkeiyama/best-todo-app/issues/7 https://github.com/tkeiyama/best-todo-app/issues/14
- [x] remove items that are completed // same as the above
- [x] Authentication: Multi-user login https://github.com/tkeiyama/best-todo-app/issues/10
